Repository MSCKIIT/MSCxHacktoberfest, pull requests merged in 2021-10, with the labels that each got.

#15 Contributing.md added
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#18 init README for MSCxHacktoberFest
  README.md
  utils/hacktober-fest-2021.svg
Labels: documentation, enhancement, Hacktoberfest, hacktoberfest-accepted

#19 init README #18
  README.md
Labels: documentation, enhancement, Hacktoberfest, hacktoberfest-accepted

#22 Add Grandpa Spoon
  Grandpa Spoon/Grandpa Spoon.png
Labels: Hacktoberfest, hacktoberfest-accepted

#21 Added Rock Paper Scissors Game
  Rock Paper Scissors Game/app.js
  Rock Paper Scissors Game/images/Paper.png
  Rock Paper Scissors Game/images/Rock.png
  Rock Paper Scissors Game/images/Scissors.png
  Rock Paper Scissors Game/index.html
  Rock Paper Scissors Game/style.css
  To-do webpage/script (BT1000097019's conflicted copy 2021-08-01).js
  To-do webpage/script.js
  To-do webpage/todo (BT1000097019's conflicted copy 2021-08-01).css
  To-do webpage/todo (BT1000097019's conflicted copy 2021-08-01).html
  To-do webpage/todo.css
  To-do webpage/todo.html
Labels: Hacktoberfest, hacktoberfest-accepted

#24 Add 7 Segment Display
  7 Segment Display/7-Segment-Display.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#25 Added To-do webpage
  To-do webpage/index.html
  To-do webpage/script.js
  To-do webpage/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#26 INITIAL COMMIT
  Meme generator/README.md
  Meme generator/package-lock.json
  Meme generator/package.json
  Meme generator/public/index.html
  Meme generator/src/App.jsx
  Meme generator/src/components/Meme.jsx
  Meme generator/src/components/Templates.jsx
  Meme generator/src/index.js
  Meme generator/src/styles/App.css
  Quiz web app/index.html
  Quiz web app/script.js
  Quiz web app/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#28 Add Weather App
  Weather App/README.md
  Weather App/package-lock.json
  Weather App/package.json
  Weather App/public/index.html
  Weather App/src/App.jsx
  Weather App/src/index.js
  Weather App/src/styles/App.css
Labels: Hacktoberfest, hacktoberfest-accepted

#27 Added Bulb glow
  Bulbglow/Bulb off.png
  Bulbglow/Bulb on.png
  Bulbglow/README.md
  Bulbglow/index.html
  Bulbglow/styles.css
Labels: Hacktoberfest, beginner-friendly, hacktoberfest-accepted, javascript

#31 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted

#30 Added grocery list maker
  grocery_list/app.js
  grocery_list/index.html
  grocery_list/logo.svg
  grocery_list/styles.css
Labels: documentation, Hacktoberfest, hacktoberfest-accepted, javascript

#49 Initialize README.md
  7 Segment Display/README.md
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#53 Initialize README.md
  Covid Tracker/README.md
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#58 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#56 add README.md to grocery_list
  Meme generator/README.md
  grocery_list/README.md
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#59 Add CONTRIBUTING.md
  Desktop-Weather-App/CONTRIBUTING.md
  Meme generator/CONTRIBUTING.md
Labels: documentation, Hacktoberfest, beginner-friendly, hacktoberfest-accepted

#70 Algorithms Hub Added
  Algorithms Hub/CONTRIBUTING.md
  Algorithms Hub/ClassicalAlgos/Kosaraju'sAlgo/kosarajus.cpp
  Algorithms Hub/ClassicalAlgos/dijkstra's_algo/dijkstra.cpp
  Algorithms Hub/ClassicalAlgos/kadane's_algorithm/Kadane's_Algorithm.py
  Algorithms Hub/ClassicalAlgos/kadane's_algorithm/readme.md
  Algorithms Hub/ClassicalAlgos/tries/tries.cpp
  Algorithms Hub/Readme.md
  Algorithms Hub/searchingAlgo/binarySearch/BinarySearchWithDuplicateElements.cpp
  Algorithms Hub/searchingAlgo/binarySearch/readme.md
  Algorithms Hub/searchingAlgo/exponentialSearch/exponentialSearch.py
  Algorithms Hub/searchingAlgo/fibonacciSearch/FibonacciSearch.cs
  Algorithms Hub/searchingAlgo/fibonacciSearch/fibonacciSearch.py.py
  Algorithms Hub/searchingAlgo/interpolationSearch/interpolationSearch.py
  Algorithms Hub/searchingAlgo/jumpSearch/jumpSearch.py
  Algorithms Hub/searchingAlgo/kmpSearch/kmpSearch.py
  Algorithms Hub/searchingAlgo/linearSearch/linearSearch.cpp
  Algorithms Hub/searchingAlgo/rabinKarpSearch/rabinKarp.cpp
  Algorithms Hub/searchingAlgo/sublistSearch/SublistSearch.cpp
  Algorithms Hub/searchingAlgo/ternarySearch/ternarySearch.py
  Algorithms Hub/sortingAlgo/ShellSort/ShellSort.py
  Algorithms Hub/sortingAlgo/bubbleSort/bubbleSort.cpp
  Algorithms Hub/sortingAlgo/bucketsort/BucketSort.cpp
  Algorithms Hub/sortingAlgo/combSort/combSort.cpp
  Algorithms Hub/sortingAlgo/countingSort/countingSort.cpp
  Algorithms Hub/sortingAlgo/cycleSort/cycleSort.cpp
  Algorithms Hub/sortingAlgo/heapSort/heapSort.cpp
  Algorithms Hub/sortingAlgo/insertionSort/insertionSort.py
  Algorithms Hub/sortingAlgo/mergeSort/MergeSortC++.cpp
  Algorithms Hub/sortingAlgo/mergeSort/Readme.md
  Algorithms Hub/sortingAlgo/pigeonholeSort/pigeonholeSort.java
  Algorithms Hub/sortingAlgo/quickSort/README.md
  Algorithms Hub/sortingAlgo/quickSort/quickSort.cpp
  Algorithms Hub/sortingAlgo/radixSort/radixSort.cpp
  Algorithms Hub/sortingAlgo/selectionSort/selectionSort.py
  Algorithms Hub/sortingAlgo/timSort/timSort.cpp
Labels: good first issue, Hacktoberfest, beginner-friendly, hacktoberfest-accepted, algorithms, javascript, python, cpp, java

#104 Add simple memory game - Simon
  .DS_Store
  SimonMemoryGame/.DS_Store
  SimonMemoryGame/index.html
  SimonMemoryGame/index.js
  SimonMemoryGame/sounds/blue.mp3
  SimonMemoryGame/sounds/green.mp3
  SimonMemoryGame/sounds/red.mp3
  SimonMemoryGame/sounds/wrong.mp3
  SimonMemoryGame/sounds/yellow.mp3
  SimonMemoryGame/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#65 Update README.md
  7 Segment Display/README.md
  Covid Tracker/README.md
  Grandpa Spoon/README.md
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#103 Added QUICK_SORT ALGO
  2048/app.js
  2048/index.html
  2048/style.css
  Algorithms Hub/sortingAlgo/quickSort/quickSort.py
Labels: Hacktoberfest, hacktoberfest-accepted

#62 added CONTRIBUTING.md
  YourTextSite/.gitignore
  YourTextSite/CONTRIBUTING.md
  YourTextSite/README.md
  YourTextSite/package-lock.json
  YourTextSite/package.json
  YourTextSite/public/favicon.ico
  YourTextSite/public/index.html
  YourTextSite/public/logo192.png
  YourTextSite/public/logo512.png
  YourTextSite/public/manifest.json
  YourTextSite/public/robots.txt
  YourTextSite/src/App.css
  YourTextSite/src/App.js
  YourTextSite/src/App.test.js
  YourTextSite/src/components/About.js
  YourTextSite/src/components/Alert.js
  YourTextSite/src/components/Navbar.js
  YourTextSite/src/components/TextForm.css
  YourTextSite/src/components/TextForm.js
  YourTextSite/src/index.css
  YourTextSite/src/index.js
  YourTextSite/src/logo.svg
  YourTextSite/src/reportWebVitals.js
  YourTextSite/src/setupTests.js
  YourTextSite/yarn.lock
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#63 Added documentation for Rock Paper Scissors Game
  Rock Paper Scissors Game/README.md
  To-do webpage/README.md
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#68 added react based jokes app
  joke_app/README.md
  joke_app/package-lock.json
  joke_app/package.json
  joke_app/public/favicon.ico
  joke_app/public/index.html
  joke_app/public/logo192.png
  joke_app/public/logo512.png
  joke_app/public/manifest.json
  joke_app/public/robots.txt
  joke_app/src/App.css
  joke_app/src/App.js
  joke_app/src/App.test.js
  joke_app/src/index.css
  joke_app/src/index.js
  joke_app/src/laugh.jpg
  joke_app/src/logo.svg
  joke_app/src/reportWebVitals.js
  joke_app/src/setupTests.js
Labels: Hacktoberfest, hacktoberfest-accepted, html-css, reactjs

#110 JS CLOCK
  JS CLOCK/index.html
  JS CLOCK/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#108 Add files via upload
  Simon_Game/app.js
  Simon_Game/index.html
  Simon_Game/sounds/blue.mp3
  Simon_Game/sounds/green.mp3
  Simon_Game/sounds/red.mp3
  Simon_Game/sounds/wrong.mp3
  Simon_Game/sounds/yellow.mp3
  Simon_Game/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#107 Added counting sort algo using python
  Algorithms Hub/sortingAlgo/countingSort/countingSort.py
Labels: Hacktoberfest, hacktoberfest-accepted

#60 Added amazon clone
  Amazon-Clone/.firebase/hosting.YnVpbGQ.cache
  Amazon-Clone/.firebaserc
  Amazon-Clone/.gitignore
  Amazon-Clone/README.md
  Amazon-Clone/firebase.json
  Amazon-Clone/package-lock.json
  Amazon-Clone/package.json
  Amazon-Clone/public/amazon-logo.png
  Amazon-Clone/public/favicon.ico
  Amazon-Clone/public/index.html
  Amazon-Clone/public/logo192.png
  Amazon-Clone/public/logo512.png
  Amazon-Clone/public/manifest.json
  Amazon-Clone/public/robots.txt
  Amazon-Clone/src/App.css
  Amazon-Clone/src/App.js
  Amazon-Clone/src/Components/Checkout.css
  Amazon-Clone/src/Components/Checkout.js
  Amazon-Clone/src/Components/CheckoutProduct.css
  Amazon-Clone/src/Components/CheckoutProduct.js
  Amazon-Clone/src/Components/Home.css
  Amazon-Clone/src/Components/Home.js
  Amazon-Clone/src/Components/Login.css
  Amazon-Clone/src/Components/Login.js
  Amazon-Clone/src/Components/Navbar.css
  Amazon-Clone/src/Components/Navbar.js
  Amazon-Clone/src/Components/Products.css
  Amazon-Clone/src/Components/Products.js
  Amazon-Clone/src/Components/Reducer.js
  Amazon-Clone/src/Components/StateProvider.js
  Amazon-Clone/src/Components/Subtotal.css
  Amazon-Clone/src/Components/Subtotal.js
  Amazon-Clone/src/firebase.js
  Amazon-Clone/src/index.css
  Amazon-Clone/src/index.js
  Amazon-Clone/src/reportWebVitals.js
Labels: Hacktoberfest, beginner-friendly, hacktoberfest-accepted, html-css

#98 Documentation Added
  Heath App/README.md
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#79 Scientific-calculator project added
  Scientific-Calculator/README.md
  Scientific-Calculator/index.html
  Scientific-Calculator/script.js
  Scientific-Calculator/style.css
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#78 Create CONTRIBUTING.md
  KnowU Personality Test App/CONTRIBUTING.md
Labels: Hacktoberfest, hacktoberfest-accepted

#74 IMDB Reviews Sentiment Analysis
  IMDB-sentiment analysis/IMDB Sentiment Analysis
  IMDB-sentiment analysis/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#112 Added insertion sort
  Algorithms Hub/sortingAlgo/insertionSort/insertion.c
Labels: Hacktoberfest, hacktoberfest-accepted

#69 Body Mass Index Calculator
  BMICalculator/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#67 Re-edited the file as instructed
  Quotes App/Readme.md
  Quotes App/background.png
  Quotes App/face.png
  Quotes App/kanye.png
  Quotes App/main.py
Labels: Hacktoberfest, hacktoberfest-accepted

#115 readme added and some small changes for beginner js quiz
  Beginner Javascript Quiz/Homepage.html
  Beginner Javascript Quiz/Readme.md
  Beginner Javascript Quiz/Script.js
  Beginner Javascript Quiz/homepage.css
  Beginner Javascript Quiz/index.html
  Beginner Javascript Quiz/quiz.html
  Beginner Javascript Quiz/results.html
  Beginner Javascript Quiz/style.css
Labels: documentation, hacktoberfest-accepted, javascript

#117 Selection Sort in C
  Algorithms Hub/sortingAlgo/selectionSort/SelectionSort.c
Labels: Hacktoberfest, hacktoberfest-accepted, algorithms, cpp

#119 Added C++ file for Interpolation Search
  Algorithms Hub/searchingAlgo/interpolationSearch/Interpolation Search.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, algorithms, cpp

#120 MergeSort Algo in C added
  Algorithms Hub/sortingAlgo/mergeSort/MergeSort.c
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, algorithms, cpp

#121 Exponential Search in C
  Algorithms Hub/searchingAlgo/exponentialSearch/exponentialSearch.c
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, algorithms

#118 fixed typo in code
  Block-Manupulation/script.js
Labels: bug, hacktoberfest-accepted, javascript

#114 To do App
  To do App/README.md
  To do App/package-lock.json
  To do App/package.json
  To do App/public/index.html
  To do App/src/App.jsx
  To do App/src/actions/index.jsx
  To do App/src/components/AddTodo.jsx
  To do App/src/components/ListTodo.jsx
  To do App/src/index.js
  To do App/src/reducer/index.js
  To do App/src/reducer/todoReducer.jsx
  To do App/src/store.jsx
  To do App/src/styles/App.css
Labels: Hacktoberfest, hacktoberfest-accepted, html-css, reactjs

#130 Add COLOR FLIPPER
  COLOR FLIPPER/README.md
  COLOR FLIPPER/app.js
  COLOR FLIPPER/hex.html
  COLOR FLIPPER/hex.js
  COLOR FLIPPER/index.html
  COLOR FLIPPER/styles.css
Labels: Hacktoberfest, beginner-friendly, hacktoberfest-accepted, javascript, html-css

#129 added binary search in java to algorithms hub
  Algorithms Hub/searchingAlgo/binarySearch/BinarySearch.java
Labels: Hacktoberfest, hacktoberfest-accepted

#131 Add Dots and Boxes
  Dots and Boxes/Dots-and-Boxes.py
  Dots and Boxes/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#133 3d solar system
  Solar_System/README.md
  Solar_System/index.html
Labels: Hacktoberfest, beginner-friendly, hacktoberfest-accepted, html-css

#134 Updated css
  .vscode/settings.json
  Beginner Javascript Quiz/quiz.html
  Beginner Javascript Quiz/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, html-css

#135 ADD reactWeb
  ReactWeb/README.md
  ReactWeb/package-lock.json
  ReactWeb/package.json
  ReactWeb/public/index.html
  ReactWeb/src/App.jsx
  ReactWeb/src/context/AuthContext.jsx
  ReactWeb/src/index.js
  ReactWeb/src/router/About.jsx
  ReactWeb/src/router/Dashboard.jsx
  ReactWeb/src/router/Home.jsx
  ReactWeb/src/router/Profile.jsx
  ReactWeb/src/styles/App.css
Labels: Hacktoberfest, beginner-friendly, hacktoberfest-accepted, html-css, reactjs

#136 Add the code of bubble sort in javascript
  Algorithms Hub/sortingAlgo/bubbleSort/bubblesort.js
Labels: Hacktoberfest, hacktoberfest-accepted, algorithms, javascript

#138 Add the code of Bubble Sort in C
  Algorithms Hub/sortingAlgo/bubbleSort/BubbleSort.c
Labels: hacktoberfest-accepted, algorithms

#137 Add border and styling to the text output area
  YourTextSite/src/components/TextForm.css
  YourTextSite/src/components/TextForm.js
Labels: Hacktoberfest, beginner-friendly, hacktoberfest-accepted

#151 Add the code for C++, Java and C
  Algorithms Hub/sortingAlgo/ShellSort/shellsort.c
  Algorithms Hub/sortingAlgo/ShellSort/shellsort.cpp
  Algorithms Hub/sortingAlgo/ShellSort/shellsort.java
Labels: hacktoberfest-accepted, algorithms, cpp, java

#143 Add Bucket Sort
  Algorithms Hub/sortingAlgo/bucketsort/Bucket-Sort.c
Labels: hacktoberfest-accepted

#149 countingSort in JS
  Algorithms Hub/sortingAlgo/countingSort/countingSort.js
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted, algorithms, java

#153 countingSort in Java
  Algorithms Hub/sortingAlgo/countingSort/countingSort.java
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted, algorithms, java

#154 Linear Search Algo in C
  Algorithms Hub/searchingAlgo/linearSearch/LinearSearch.c
Labels: documentation, enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted, algorithms, cpp

#156 added sublist search using python
  Algorithms Hub/searchingAlgo/sublistSearch/SublistSearch.py
Labels: Hacktoberfest, hacktoberfest-accepted

#155 Added bubble sort algorithm in java
  Algorithms Hub/sortingAlgo/bubbleSort/bubbleSort.java
  DiceGame/.project
  DiceGame/.settings/org.eclipse.buildship.core.prefs
Labels: Hacktoberfest, hacktoberfest-accepted, algorithms, java

#157 LinearSearch Algo in Python added
  Algorithms Hub/searchingAlgo/linearSearch/LinearSearchPython.py
  Algorithms Hub/sortingAlgo/insertionSort/InsertionSort.cpp
Labels: documentation, enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted, algorithms, cpp

#167 Add Binary Search
  Algorithms Hub/searchingAlgo/binarySearch/Binary-Search.cpp
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted, algorithms, cpp

#169 Add Binary Search
  Algorithms Hub/searchingAlgo/binarySearch/Binary-Search.c
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted, algorithms

#152 Add binary search java code
  Algorithms Hub/searchingAlgo/binarySearch/binarySearch.java
Labels: Hacktoberfest, hacktoberfest-accepted, algorithms

#161 Jump
  Algorithms Hub/searchingAlgo/jumpSearch/jumpSearch.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, algorithms, cpp

#158 Added Dictionary app made with React.js
  Dictionary app/README.md
  Dictionary app/package-lock.json
  Dictionary app/package.json
  Dictionary app/public/favicon.ico
  Dictionary app/public/index.html
  Dictionary app/public/logo192.png
  Dictionary app/public/logo512.png
  Dictionary app/public/manifest.json
  Dictionary app/public/robots.txt
  Dictionary app/src/App.css
  Dictionary app/src/App.js
  Dictionary app/src/App.test.js
  Dictionary app/src/index.css
  Dictionary app/src/index.js
  Dictionary app/src/logo.svg
  Dictionary app/src/reportWebVitals.js
  Dictionary app/src/setupTests.js
Labels: Hacktoberfest, hacktoberfest-accepted, reactjs

#159 adding a crypto currency app
  cryptoCurrency_app/README.md
  cryptoCurrency_app/package-lock.json
  cryptoCurrency_app/package.json
  cryptoCurrency_app/public/favicon.ico
  cryptoCurrency_app/public/index.html
  cryptoCurrency_app/public/logo192.png
  cryptoCurrency_app/public/logo512.png
  cryptoCurrency_app/public/manifest.json
  cryptoCurrency_app/public/robots.txt
  cryptoCurrency_app/src/App.css
  cryptoCurrency_app/src/App.js
  cryptoCurrency_app/src/Coin.css
  cryptoCurrency_app/src/Coin.js
  cryptoCurrency_app/src/index.js
Labels: Hacktoberfest, hacktoberfest-accepted

#163 new UI developed for Quiz App
  .DS_Store
  Beginner Javascript Quiz/Homepage.html
  Beginner Javascript Quiz/homepage.css
Labels: Hacktoberfest, beginner-friendly, hacktoberfest-accepted, html-css

#185 Update testimonial-section
  TinDog/css/styles.css
Labels: hacktoberfest-accepted

#198 Comb sort code added in js
  Algorithms Hub/sortingAlgo/combSort/CombSort.js
Labels: Hacktoberfest, hacktoberfest-accepted

#199 ternary search code added in js
  Algorithms Hub/searchingAlgo/ternarySearch/TernarySearch.js
Labels: Hacktoberfest, hacktoberfest-accepted

#200 Added Sublist search algo code in js
  Algorithms Hub/searchingAlgo/sublistSearch/SublistSearch.js
Labels: Hacktoberfest, hacktoberfest-accepted

#202 Added Jump search algo in js
  Algorithms Hub/searchingAlgo/jumpSearch/JumpSearch.js
Labels: Hacktoberfest, hacktoberfest-accepted

#201 Added some design to the score board of rock-paper-scissor game
  Rock Paper Scissors Game/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#204 Fibonacci Search algo code added in js
  Algorithms Hub/searchingAlgo/fibonacciSearch/FibonacciSearch.js
Labels: Hacktoberfest, hacktoberfest-accepted

#203 Added ternary searching using cpp
  Algorithms Hub/searchingAlgo/ternarySearch/ternarySearch.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#205 Improved the CSS of the Drum Kit Project_146
  Drum Kit/images/a.png
  Drum Kit/images/d.png
  Drum Kit/images/j.png
  Drum Kit/images/k.png
  Drum Kit/images/l.png
  Drum Kit/images/s.png
  Drum Kit/images/w.png
  Drum Kit/index.html
  Drum Kit/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#208 Added Radix Sort in python
  Algorithms Hub/sortingAlgo/radixSort/radixSort.py
Labels: Hacktoberfest, hacktoberfest-accepted

#209 Functionality to add a new task by Enter Key
  To-do webpage/index.html
  To-do webpage/script.js
Labels: Hacktoberfest, hacktoberfest-accepted

#212 Added JAVA Code for 7 Segment Display
  7 Segment Display/7-Segment-Display.java
Labels: Hacktoberfest, hacktoberfest-accepted, java

#210 Added a Readme file
  DiceGame/Readme.md
  DiceGame/readme.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#150 Converting-Images-to-ASCII
  Converting-images-to-ASCII--main/Output.txt
  Converting-images-to-ASCII--main/README.md
  Converting-images-to-ASCII--main/ascii.py
  Converting-images-to-ASCII--main/car.jpg
  Converting-images-to-ASCII--main/output.png
Labels: Hacktoberfest, hacktoberfest-accepted

#214 Added Dijkstra algo in cpp (Fixed Issue #102)
  Algorithms Hub/ClassicalAlgos/dijkstra's_algo/Dijkstra's_algo.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, algorithms

#211 Algorithm of HeapSort in Java, js and HeapSort.
  Algorithms Hub/sortingAlgo/cycleSort/Cyclesort.java
  Algorithms Hub/sortingAlgo/cycleSort/Cyclesort.js
  Algorithms Hub/sortingAlgo/cycleSort/Cyclesort.py
  Algorithms Hub/sortingAlgo/heapSort/HeapSort.java
  Algorithms Hub/sortingAlgo/heapSort/HeapSort.js
  Algorithms Hub/sortingAlgo/heapSort/HeapSort.py
Labels: Hacktoberfest, hacktoberfest-accepted, algorithms

#207 added dijkstra algo in python
  Algorithms Hub/ClassicalAlgos/dijkstra's_algo/dijkstraalgo.py
Labels: Hacktoberfest, hacktoberfest-accepted, algorithms

#221 Added code for exponential search in c++ and js
  Algorithms Hub/searchingAlgo/exponentialSearch/ExponentialSearch.cpp
  Algorithms Hub/searchingAlgo/exponentialSearch/ExponentialSearch.js
Labels: hacktoberfest-accepted, algorithms, javascript, cpp

#222 Add Fibonacci Search
  Algorithms Hub/searchingAlgo/fibonacciSearch/Fibonacci-Search.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, algorithms, cpp

#141 Added Insect hit game file
  insect_hit_game/index.html
  insect_hit_game/script.js
  insect_hit_game/style.css
Labels: Hacktoberfest, hacktoberfest-accepted, javascript

#230 Rabin Karp and Binary Search added
  Algorithms Hub/searchingAlgo/binarySearch/binarySearch.java
  Algorithms Hub/searchingAlgo/rabinKarpSearch/rabinKarp.java
Labels: Hacktoberfest, hacktoberfest-accepted

#231 Fixed Issue #35
  Calculator/Readme.md
  Calculator/calc.png
Labels: Hacktoberfest, hacktoberfest-accepted

#233 Add Pigeonhole Sort
  Algorithms Hub/sortingAlgo/pigeonholeSort/Pigeonhole-Sort.py
Labels: Hacktoberfest, hacktoberfest-accepted, algorithms

#235 Made responsive and did some formatting and also some changes
  Calculator/index.html
  Calculator/style.css
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#234 Implemented Edit Functionality Of A Todo
  To-do webpage/index.html
  To-do webpage/script.js
  To-do webpage/style.css
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#248 fixes #223 issue ui
  Scientific-Calculator/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#251 Added a project
  Language Translator/Language_Translator.py
  Language Translator/Readme.md
  Language Translator/clicking.png
  Language Translator/logout.png
  Language Translator/translater.ico
Labels: Hacktoberfest, hacktoberfest-accepted

#261 merge sort cpp
  Algorithms Hub/sortingAlgo/mergeSort/merge_sort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#258 Cancer tumour size prediction model
  Cancer tumour size prediction/README.md
  Cancer tumour size prediction/model.ipynb
Labels: Hacktoberfest, hacktoberfest-accepted

#265 radix_sort.c
  Algorithms Hub/sortingAlgo/radixSort/radix_sort.c
Labels: hacktoberfest-accepted, algorithms

#264 Create CONTRIBUTING.md
  URL Minifier/CONTRIBUTING.md
Labels: documentation, enhancement, hacktoberfest-accepted

#245 Updated Packages, removed warnings in KnowU Personality Test App and added combsort.py in Algorithms Hub
  Algorithms Hub/sortingAlgo/combSort/combsort.py
  KnowU Personality Test App/lib/Details/Analysts/INTJ/tab_view.dart
  KnowU Personality Test App/lib/Details/Analysts/INTP/tab_view.dart
  KnowU Personality Test App/lib/Details/Diplomats/INFJ/tab_view.dart
  KnowU Personality Test App/lib/Details/Explorers/ISFJ/tab_view.dart
  KnowU Personality Test App/lib/Screens/Welcome/page_one.dart
  KnowU Personality Test App/lib/Screens/Welcome/page_three.dart
  KnowU Personality Test App/lib/Screens/Welcome/second_page.dart
  KnowU Personality Test App/lib/Screens/Welcome/splash_screen.dart
  KnowU Personality Test App/lib/Screens/splash_screen.dart
  KnowU Personality Test App/lib/components/switch_slider_gradients/date_picker.dart
  KnowU Personality Test App/lib/components/text_widgets/text_underline.dart
  KnowU Personality Test App/lib/main.dart
  KnowU Personality Test App/lib/personality_test/results_page.dart
  KnowU Personality Test App/pubspec.lock
  KnowU Personality Test App/pubspec.yaml
Labels: hacktoberfest-accepted

#259 Edited CSS and HTML file of Beginner JS quiz
  Beginner Javascript Quiz/quiz.html
  Beginner Javascript Quiz/style.css
Labels: Hacktoberfest, beginner-friendly, hacktoberfest-accepted, html-css

#271 made the website responsive and also fix the bug of x and y transformation
  Block-Manupulation/index.html
  Block-Manupulation/style.css
Labels: good first issue, hacktoberfest-accepted, html-css

#266 Implemented ROT13 functionality in YourTextSite Project
  YourTextSite/src/components/TextForm.js
Labels: Hacktoberfest, hacktoberfest-accepted

#279 Binary Search in JS
  Algorithms Hub/searchingAlgo/binarySearch/binarySearch.js
Labels: Hacktoberfest, hacktoberfest-accepted

#284 merge sort in java
  Algorithms Hub/searchingAlgo/binarySearch/BinarySearch.java
  Algorithms Hub/searchingAlgo/binarySearch/binarySearch.java
  Algorithms Hub/sortingAlgo/mergeSort/MergeSort.class
  Algorithms Hub/sortingAlgo/mergeSort/mergesort.java
Labels: Hacktoberfest, hacktoberfest-accepted

#272 Created a drum roll music game
  Drumbeat game/.DS_Store
  Drumbeat game/images/crash.png
  Drumbeat game/images/kick.png
  Drumbeat game/images/snare.png
  Drumbeat game/images/tom1.png
  Drumbeat game/images/tom2.png
  Drumbeat game/images/tom3.png
  Drumbeat game/images/tom4.png
  Drumbeat game/index.html
  Drumbeat game/index.js
  Drumbeat game/readme.md
  Drumbeat game/sounds/crash.mp3
  Drumbeat game/sounds/kick-bass.mp3
  Drumbeat game/sounds/snare.mp3
  Drumbeat game/sounds/tom-1.mp3
  Drumbeat game/sounds/tom-2.mp3
  Drumbeat game/sounds/tom-3.mp3
  Drumbeat game/sounds/tom-4.mp3
  Drumbeat game/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#278 added ternary search code in java
  Algorithms Hub/searchingAlgo/ternarySearch/ternarySearch.java
Labels: Hacktoberfest, hacktoberfest-accepted

#289 Color Game Project Added
  Color-Game/README.md
  Color-Game/color_game.py
  Color-Game/img1.png
Labels: documentation, Hacktoberfest, beginner-friendly, hacktoberfest-accepted, python

#283 bucketSort in Python
  Algorithms Hub/searchingAlgo/binarySearch/BinarySearch.class
Labels: Hacktoberfest, hacktoberfest-accepted

#292 Music Player Issue Solved
  Music_Player/Contributors.md.txt
  Music_Player/music_player.py
Labels: documentation, enhancement, good first issue, Hacktoberfest, beginner-friendly, hacktoberfest-accepted, algorithms, python

#286 Solved the login issue in index.html
  Beginner Javascript Quiz/Script.js
Labels: beginner-friendly, hacktoberfest-accepted, javascript

#288 added count sort in c#
  Algorithms Hub/sortingAlgo/countingSort/countingSort.cs
Labels: hacktoberfest-accepted, algorithms

#305 Add Pigeonhole Sort
  Algorithms Hub/sortingAlgo/pigeonholeSort/PigeonholeSort.c
Labels: hacktoberfest-accepted, algorithms

#302 Added Counter keeper
  counter/README.md
  counter/app.js
  counter/index.html
  counter/styles.css
Labels: hacktoberfest-accepted, javascript

#314 improved UI of the page
  Rock Paper Scissors Game/style.css
Labels: hacktoberfest-accepted
